# Development Related Tools
- hosts: localhost
  connection: local
  tasks:
    - name: Install RPM Fusion free gpg key
      become: true
      ansible.builtin.rpm_key:
       key: https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-fedora-2020
       state: present

    - name: Install RPM Fusion
      become: true
      dnf:
        name: "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ansible_distribution_major_version}}.noarch.rpm"
        state: present
    
    - name: Install VSCode
      include_role: 
        name: vscode

    - name: Install Kitty Terminal Emulator
      become: true
      dnf: 
        name: kitty
        state: latest

    - name: Install Git
      become: true
      dnf:
       name: git
       state: latest

    - name: Install NeoVim
      become: true
      dnf:
        name: neovim
        state: latest

    - name: Install NodeJS
      become: true
      dnf:
        name: nodejs
        state: latest

    - name: Install Python
      become: true
      dnf:
        name: python
        state: latest
    
    - name: Install CMake
      become: true
      dnf:
        name: cmake
        state: latest

    - name: Install G++
      become: true
      dnf:
        name: g++
        state: latest

    - name: Install SQLite Browser
      become: true
      dnf:
        name: sqlitebrowser
        state: latest


    


    
