# General Applications
- hosts: localhost
  connection: local
  tasks:
    - name: Install Firefox
      import_role:
        name: firefox

    - name: Add Flathub Repo
      shell: sudo flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
      changed_when: false

    - name: Install Obsidian
      community.general.flatpak:
        name:  https://dl.flathub.org/repo/appstream/md.obsidian.Obsidian.flatpakref
        state: latest

    - name: Install Discord
      community.general.flatpak:
        name: https://dl.flathub.org/repo/appstream/com.discordapp.Discord.flatpakref
        state: latest

    - name: Install Mission Center
      community.general.flatpak:
        name: https://dl.flathub.org/repo/appstream/io.missioncenter.MissionCenter.flatpakref
        state: latest

    - name: Install Steam
      become: true
      ansible.builtin.dnf:
        name: steam
        state: latest

    - name: Install Wireguard
      become: true
      ansible.builtin.dnf:
        name: wireguard-tools
        state: latest

    - name: Install Solaar
      become: true
      ansible.builtin.dnf:
        name: solaar
        state: latest

    - name: Install Syncthing
      become: true
      community.general.flatpak:
        name: https://dl.flathub.org/repo/appstream/com.github.zocker_160.SyncThingy.flatpakref
        state: latest

    - name: Install Anki
      become: true
      community.general.flatpak:
        name: https://dl.flathub.org/repo/appstream/net.ankiweb.Anki.flatpakref
        state: latest

    - name: Install Signal
      become: true
      community.general.flatpak:
        name: https://dl.flathub.org/repo/appstream/org.signal.Signal.flatpakref
        state: latest

    - name: Install Thunderbird
      become: true
      community.general.flatpak:
        name: https://dl.flathub.org/repo/appstream/org.mozilla.Thunderbird.flatpakref
        state: latest

    - name: Install LibreOffice
      become: true
      community.general.flatpak:
        name: https://dl.flathub.org/repo/appstream/org.libreoffice.LibreOffice.flatpakref
        state: latest

    - name: Install full HEIC support
      become: true
      ansible.builtin.dnf:
        name: libheif-freeworld
        state: latest

    - name: Install Plex desktop app
      community.general.flatpak:
        name: https://dl.flathub.org/repo/appstream/tv.plex.PlexDesktop.flatpakref
        state: latest

    - name: Install Plex HTPC app
      community.general.flatpak:
        name: https://dl.flathub.org/repo/appstream/tv.plex.PlexHTPC.flatpakref
        state: latest

    - name: Install MPV
      community.general.flatpak:
        name: https://dl.flathub.org/repo/appstream/io.mpv.Mpv.flatpakref
        state: latest
    
    

              
        
      