# General Applications
- hosts: localhost
  connection: local
  tasks:
    - name: Install Firefox
      import_role:
        name: firefox

    - name: Add Flathub Repo
      shell: sudo flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
      changed_when: false

    - name: Install Obsidian
      community.general.flatpak:
        name:  https://dl.flathub.org/repo/appstream/md.obsidian.Obsidian.flatpakref
        state: latest

    - name: Install Vesktop
      community.general.flatpak:
        name: https://dl.flathub.org/repo/appstream/dev.vencord.Vesktop.flatpakref
        state: latest

    - name: Install Mission Center
      community.general.flatpak:
        name: https://dl.flathub.org/repo/appstream/io.missioncenter.MissionCenter.flatpakref
        state: latest

    - name: Install Steam
      become: true
      ansible.builtin.dnf:
        name: steam
        state: latest

    - name: Install full HEIC support
      become: true
      ansible.builtin.dnf:
        name: libheif-freeworld
        state: latest

    - name: Install Plex desktop app
      community.general.flatpak:
        name: https://dl.flathub.org/repo/appstream/tv.plex.PlexDesktop.flatpakref
        state: latest

    - name: Install Plex HTPC app
      community.general.flatpak:
        name: https://dl.flathub.org/repo/appstream/tv.plex.PlexHTPC.flatpakref
        state: latest
    

              
        
      