- name: Install Firefox from DNF
  become: true
  dnf:
    name: firefox
    state: latest

- name: Get Profiles
  shell: cat ~/.mozilla/firefox/profiles.ini
  register: Firefox_Profile_Search
  changed_when: false

- name: Search for Personal Profile
  set_fact:
    Personal_Profile_Name: "{{ Firefox_Profile_Search.stdout | regex_search('(?<=Path=)[A-z0-9]*.Personal') }}"
  when: Firefox_Profile_Search.stdout | regex_search('(?<=Path=)[A-z0-9]*.Personal')

- name: Create Personal Profile
  when: Personal_Profile_Name is not defined
  block:
    - name: Create Personal Profile
      shell: firefox -CreateProfile "Personal"
    - name: Get Profiles
      shell: cat ~/.mozilla/firefox/profiles.ini
      register: Firefox_Profile_Search_L
      changed_when: false
    - name: Get Personal Profile Name
      set_fact:
        Personal_Profile_Name: "{{ Firefox_Profile_Search_L.stdout | regex_search('(?<=Path=)[A-z0-9]*.Personal') }}" 

- name: Apply Arkenfox User.js to Personal Profile
  get_url:
    url: https://raw.githubusercontent.com/arkenfox/user.js/master/user.js
    dest: ~/.mozilla/firefox/{{ Personal_Profile_Name }}/user.js

- name: Search for School Profile
  set_fact:
    School_Profile_Name: "{{ Firefox_Profile_Search.stdout | regex_search('(?<=Path=)[A-z0-9]*.School') }}"
  when: Firefox_Profile_Search.stdout | regex_search('(?<=Path=)[A-z0-9]*.School')

- name: Create School Profile
  when: School_Profile_Name is not defined
  block:
    - name: Create School Profile
      shell: firefox -CreateProfile "School"
    - name: Get Profiles
      shell: cat ~/.mozilla/firefox/profiles.ini
      register: Firefox_Profile_Search_L
      changed_when: false
    - name: Get School Profile Name
      set_fact:
        School_Profile_Name: "{{ Firefox_Profile_Search_L.stdout | regex_search('(?<=Path=)[A-z0-9]*.School') }}"


- name: Apply Arkenfox User.js to School Profile
  get_url:
    url: https://raw.githubusercontent.com/arkenfox/user.js/master/user.js
    dest: ~/.mozilla/firefox/{{ School_Profile_Name }}/user.js

# Going to come back eventually for settings and extensions configuration
# Also want to create new desktop shortcuts for specific firefox profiles that will show in search and on taskbar
